sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  firefox: "53.0"
  chrome: stable
install:
  - travis_retry npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - jdk_switcher use oraclejdk8
  - npm run mockserver > /dev/null 2>&1 &
  - npm run webdriver > /dev/null 2>&1 &
  - sleep 5
script:
  - npm test