sudo: false
dist: trusty
language: node_js
node_js:
- '8'
addons:
  firefox: '53.0'
  chrome: stable
install:
- travis_retry npm install
- npm i -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- jdk_switcher use oraclejdk8
- npm run mockserver > /dev/null 2>&1 &
- npm run webdriver > /dev/null 2>&1 &
- sleep 5
script:
- npm test
after_script:
- greenkeeper-lockfile-upload
before_deploy:
- npm build
deploy:
  provider: npm
  email: j.andrichak@rackspace.com
  skip_cleanup: true
  api_key:
    secure: Meun6OWqibKyNwqmJzFwtrpHrSgmu66Bkbnwj9O9rCNESijTsz0HJ9aaxIxvjsCpvW/BXZOLTvACgU8eTMNu3x50GxRQjG1Ac/zG1QIaMlTa/yxXRwsyRGwrSxvGeErmLEDramfH8J16LgXkc7kXmEm9++Qz7qDlN+feIqxl8htw5RNpDmesPtKSObIBwqo9jhmaLIPlfalrVo5r4OrML0UMBisGW2sL62m3gVKgHa0WLumxIv/6wHh3aSiUdTAODYVj9pvRBkjPEwjQjZx/n+rmzBIf6otYTFEZm8a/EBvzhpe3m/OKTza930OxDzM6pleH47nSuHYjAi/NXXVvQiGWH4cneZAVtG0HxqDQiEEFj0yiJxsiRsQv7oLbOS6ygZ+tOaaZCtsIgyX2HhxlhAOQW2vF4JSYyaUuDTrWtUWEpdDe4pmRjcDcLxl5fflTR2b49reGOPCBVUqrMwzmbLTi5P2ffcBiTme2ZzpDPpzXzE84DF+Fs5NdqAyEnxxKBE0HDrxwOtYMNpiyH0AZRdSY4kBRxmshgGfnzn1FEr+sMbSGebXOu3CWIPXVX5EtIzktr2Pxzih9ryphnCKH3X5kcnJEOPfDVmEhHW1MiNEXuRXIWoVshnVxf6cSmL9HZdvqfYOMiKGjgHQ8oPh0I4VeeRkeOK2bKNpCOJ3AviA=
  on:
    tags: true
    repo: rackerlabs/snappit-visual-regression
